"""init all tables

Revision ID: bd9a3d6409b7
Revises: 
Create Date: 2026-06-18 14:44:44.080683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'bd9a3d6409b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('patterns',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.Enum('AUTH', 'ERROR_HANDLING', 'SEARCH', 'DATABASE', 'API', 'OTHER', name='patterncategory', native_enum=False, length=20), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patterns_category'), 'patterns', ['category'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('github_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', 'GUEST', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('chat_sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('inquiries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('IMPROVEMENT', 'BUG', 'OTHER', name='inquirytype', native_enum=False, length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inquiries_is_read'), 'inquiries', ['is_read'], unique=False)
    op.create_index(op.f('ix_inquiries_user_id'), 'inquiries', ['user_id'], unique=False)
    op.create_table('notices',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notices_author_id'), 'notices', ['author_id'], unique=False)
    op.create_index(op.f('ix_notices_pinned'), 'notices', ['pinned'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('CLASS', 'TEAM', 'PERSONAL', 'CONTEST', name='projectcategory', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'REJECTED', 'ARCHIVED', name='projectstatus', native_enum=False, length=20), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_table('scrap_folders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrap_folders_user_id'), 'scrap_folders', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'AI', name='messagerole', native_enum=False, length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('code_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_table('repos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('github_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('role', sa.Enum('BACKEND', 'FRONTEND', 'AI_ML', 'OTHER', name='reporole', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'INDEXING', 'ACTIVE', 'FAILED', 'ARCHIVED', name='repostatus', native_enum=False, length=20), nullable=False),
    sa.Column('last_commit_hash', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repos_project_id'), 'repos', ['project_id'], unique=False)
    op.create_table('scraps',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('folder_id', sa.BigInteger(), nullable=True),
    sa.Column('project_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('code_text', sa.Text(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('VIEWER', 'CHAT', name='scrapsource', native_enum=False, length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['scrap_folders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraps_folder_id'), 'scraps', ['folder_id'], unique=False)
    op.create_index(op.f('ix_scraps_user_id'), 'scraps', ['user_id'], unique=False)
    op.create_table('code_chunks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('repo_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('chunk_type', sa.Enum('FUNCTION', 'CLASS', 'METHOD', 'CONFIG', 'IMPORT', name='chunktype', native_enum=False, length=20), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('code_text', sa.Text(), nullable=False),
    sa.Column('code_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('desc_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('fts_tsv', postgresql.TSVECTOR(), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_chunks_project_id'), 'code_chunks', ['project_id'], unique=False)
    op.create_index(op.f('ix_code_chunks_repo_id'), 'code_chunks', ['repo_id'], unique=False)
    op.create_table('pattern_examples',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('pattern_id', sa.BigInteger(), nullable=False),
    sa.Column('repo_id', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('code_text', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pattern_examples_pattern_id'), 'pattern_examples', ['pattern_id'], unique=False)
    op.create_index(op.f('ix_pattern_examples_repo_id'), 'pattern_examples', ['repo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pattern_examples_repo_id'), table_name='pattern_examples')
    op.drop_index(op.f('ix_pattern_examples_pattern_id'), table_name='pattern_examples')
    op.drop_table('pattern_examples')
    op.drop_index(op.f('ix_code_chunks_repo_id'), table_name='code_chunks')
    op.drop_index(op.f('ix_code_chunks_project_id'), table_name='code_chunks')
    op.drop_table('code_chunks')
    op.drop_index(op.f('ix_scraps_user_id'), table_name='scraps')
    op.drop_index(op.f('ix_scraps_folder_id'), table_name='scraps')
    op.drop_table('scraps')
    op.drop_index(op.f('ix_repos_project_id'), table_name='repos')
    op.drop_table('repos')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_scrap_folders_user_id'), table_name='scrap_folders')
    op.drop_table('scrap_folders')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_notices_pinned'), table_name='notices')
    op.drop_index(op.f('ix_notices_author_id'), table_name='notices')
    op.drop_table('notices')
    op.drop_index(op.f('ix_inquiries_user_id'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_is_read'), table_name='inquiries')
    op.drop_table('inquiries')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patterns_category'), table_name='patterns')
    op.drop_table('patterns')
    # ### end Alembic commands ###
